/**
 * JHipster View Blueprint - Liquibase Generator
 * Generates createView changelog entries for View entities
 */
import BaseApplicationGenerator from 'generator-jhipster/generators/liquibase';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

export default class extends BaseApplicationGenerator {
  constructor(args, opts, features) {
    super(args, opts, { ...features, sbsBlueprint: true });
  }

  get [BaseApplicationGenerator.PREPARING_EACH_ENTITY]() {
    return this.asPreparingEachEntityTaskGroup({
      prepareViewEntity({ entity }) {
        // Check if entity has @View annotation (JHipster stores annotations in lowercase)
        const isView = entity.annotations?.view || entity.annotations?.View;
        if (isView) {
          entity.isView = true;
          entity.viewSql = entity.annotations?.sql || entity.annotations?.Sql;
          entity.viewSqlFile = entity.annotations?.sqlFile || entity.annotations?.SqlFile || entity.annotations?.sqlfile;

          this.log.info(`View entity detected: ${entity.name}`);
          if (entity.viewSql) {
            this.log.info(`  SQL: ${entity.viewSql.substring(0, 50)}...`);
          }
          if (entity.viewSqlFile) {
            this.log.info(`  SQL File: ${entity.viewSqlFile}`);
          }
        }
      },
    });
  }

  get [BaseApplicationGenerator.WRITING_ENTITIES]() {
    return this.asWritingEntitiesTaskGroup({
      async writeViewChangelogs({ application, entities }) {
        for (const entity of entities.filter(e => e.isView)) {
          await this._generateViewChangelog(application, entity);
        }
      },
    });
  }

  async _generateViewChangelog(application, entity) {
    const viewName = entity.entityTableName;
    const timestamp = this._generateTimestamp();
    const changelogFileName = `${timestamp}_create_view_${viewName}.xml`;

    let viewSql = this._resolveViewSql(entity);

    if (!viewSql) {
      this.log.warn(`No SQL found for view entity: ${entity.name}. Skipping changelog generation.`);
      return;
    }

    // Extract SELECT statement from CREATE VIEW if present
    viewSql = this._extractSelectStatement(viewSql);

    const changelogPath = `${application.srcMainResources}config/liquibase/changelog/${changelogFileName}`;

    this.log.info(`Generating view changelog: ${changelogFileName}`);

    await this.writeDestination(changelogPath, this._generateChangelogContent(viewName, viewSql, timestamp, entity));

    // Add to master changelog
    await this._addToMasterChangelog(application, changelogFileName);
  }

  _resolveViewSql(entity) {
    // First try inline SQL
    if (entity.viewSql) {
      return entity.viewSql;
    }

    // Then try SQL file
    if (entity.viewSqlFile) {
      const sqlFilePath = join(this.destinationPath(), entity.viewSqlFile);
      if (existsSync(sqlFilePath)) {
        return readFileSync(sqlFilePath, 'utf8');
      } else {
        this.log.warn(`SQL file not found: ${entity.viewSqlFile}`);
      }
    }

    return null;
  }

  _extractSelectStatement(sql) {
    // If it's a CREATE VIEW statement, extract the SELECT part
    const createViewMatch = sql.match(/CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+\w+\s+AS\s+(.+)/is);
    if (createViewMatch) {
      return createViewMatch[1].trim();
    }
    // Otherwise return as-is (assume it's already a SELECT statement)
    return sql.trim();
  }

  _generateChangelogContent(viewName, viewSql, timestamp, entity) {
    return `<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <!--
        Database view for entity: ${entity.entityClass}
        Generated by JHipster View Blueprint
    -->
    <changeSet id="${timestamp}-create-view-${viewName}" author="jhipster-view-blueprint">
        <createView viewName="${viewName}" replaceIfExists="true">
            ${viewSql}
        </createView>
    </changeSet>

</databaseChangeLog>
`;
  }

  _generateTimestamp() {
    const now = new Date();
    const pad = n => String(n).padStart(2, '0');
    return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  }

  async _addToMasterChangelog(application, changelogFileName) {
    const masterChangelogPath = `${application.srcMainResources}config/liquibase/master.xml`;

    if (!this.existsDestination(masterChangelogPath)) {
      this.log.warn('Master changelog not found. Please add the view changelog manually.');
      return;
    }

    const includeEntry = `    <include file="config/liquibase/changelog/${changelogFileName}" relativeToChangelogFile="false"/>`;

    this.editFile(masterChangelogPath, content => {
      if (content.includes(changelogFileName)) {
        return content;
      }

      // Add before closing tag
      return content.replace(
        /(<\/databaseChangeLog>)/,
        `${includeEntry}\n$1`
      );
    });
  }
}
